import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import StyledComponentsRegistry from '../../lib/AntdRegistry'
import theme from '../../theme/themeConfig';
import { ConfigProvider } from '../../lib/antd';
import { Button, Input, Layout, MenuProps, Space } from 'antd';
import Image from 'next/image'
import { DownOutlined, SearchOutlined, SmileOutlined } from '@ant-design/icons'
import Dropdown from 'antd/es/dropdown/dropdown'
import LayoutHeader from '../components/header'
import AppLayout from '../components/layout';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <ConfigProvider theme={theme}>
            <AppLayout>
              {children}
            </AppLayout>
          </ConfigProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}

